### PR TITLE
Patrick K's Daily Code Challenges: primePalindrome

### PR DESCRIPTION
**Pull request by mixelpixel**
GitHub is saying it can't "automatically merge" so I copied the 2nd days challenge (isUnique) folder from a .zip download instead of using `git pull remote master` to update into my local repositories master branch.

### CODE REVIEW

**Comment by mixelpixel** [comment]
Interesting... I presume the code made it to your end and you can access the data? This is as far as I can get from having manually downloaded the updates in a .zip file ...

**Comment by ryan-hamblin** [comment]
Yeah I can see all your code and changes. I think what we're going to do, is keep forking/cloning and then just adding a remote upstream to each fork. We'll get back to you on what we set up.

**Comment by mixelpixel** [comment]
Cool - thanks 4 the feedback!

**Comment by mixelpixel** [comment]
One significant change to the procedure compared to what you posted during the Brown Bag

**Comment by ryan-hamblin** [comment]
Alright. We will have to settle in on a solution to these issues. I'm looping ben in on this.

**Comment by mixelpixel** [comment]
reverseCase passes. Has comments. Could be refactored to ES6-style conditional

**Review by ryan-hamblin — COMMENTED** [review]
So I see you've crafted two algorithms here. They're very well put together. Now how would you add them together to check the greatest palindrome, that is prime, between 1 - 1000?

**Pull request closed without merging**
